### ISSUE TITLE
Candidate update queries for existing records

### ISSUE THREAD

**Issue by jegreely** [bullhorn/dataloader#29]
Error below:

`INFO: Querying for https://rest0.bullhornstaffing.com/rest-services/yh99g/search
/Candidate?fields=id&query=isDeleted%3A%22false%22+AND+name%3A%22%27Lorenzo+Liga
to%27%22+AND+id%3A%2216637%22+AND+email%3A%22%27lorenzoligato%40icloud.com%27%22
&count=2&useV2=true&BhRestToken=cad4acbc-147c-479b-9359-f9b062c9e7e1
Feb 25, 2016 8:31:43 AM com.bullhorn.dataloader.service.api.BullhornApiUpdater g
etCall
INFO: Querying for https://rest0.bullhornstaffing.com/rest-services/yh99g/query/
Candidate?fields=id&where=id%3D16637&count=2&BhRestToken=cad4acbc-147c-479b-9359
-f9b062c9e7e1
Exception in thread "pool-1-thread-3" com.google.common.util.concurrent.Unchecke
dExecutionException: org.json.JSONException: JSONObject["count"] not found.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.j
ava:4824)
        at com.bullhorn.dataloader.service.executor.JsonService.createOrGetEntit
y(JsonService.java:95)
        at com.bullhorn.dataloader.service.executor.JsonService.run(JsonService.
java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.json.JSONException: JSONObject["count"] not found.
        at org.json.JSONObject.get(JSONObject.java:477)
        at org.json.JSONObject.getInt(JSONObject.java:604)
        at com.bullhorn.dataloader.service.api.BullhornApiUpdater.idExistsInRest
(BullhornApiUpdater.java:99)
        at com.bullhorn.dataloader.service.api.BullhornApiUpdater.idExistsButNot
InRest(BullhornApiUpdater.java:94)
        at com.bullhorn.dataloader.service.api.BullhornApiUpdater.merge(Bullhorn
ApiUpdater.java:28)
        at com.bullhorn.dataloader.service.query.EntityCache.load(EntityCache.ja
va:57)
        at com.bullhorn.dataloader.service.query.EntityCache.load(EntityCache.ja
va:37)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(L
ocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2
319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache
.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 8 more
`

**Comment by njuszczak** [comment]
The issue is there is a space between "search" and "/Candidate". Not sure what is causing it.

**Comment by rmcdole** [comment]
fixed
