### ISSUE TITLE
"fields" not found exception

### ISSUE THREAD

**Issue by ccoffman1** [bullhorn/dataloader#30]
Hello,

I've setup DataLoader on my machine in order to troubleshoot an issue and I have gotten stuck where it is giving me the following error (the same happens when I am attempting to create new and update existing):

```
Apr 22, 2016 4:39:16 PM com.bullhorn.dataloader.service.api.BullhornAPI frontLoa
d
INFO: Front loading clientContact
Exception in thread "main" org.json.JSONException: JSONObject["fields"] not foun
d.
        at org.json.JSONObject.get(JSONObject.java:477)
        at org.json.JSONObject.getJSONArray(JSONObject.java:624)
        at com.bullhorn.dataloader.service.api.BullhornAPI.getFieldsFromMetaResp
onse(BullhornAPI.java:369)
        at com.bullhorn.dataloader.service.api.BullhornAPI.getMetaDataTypes(Bull
hornAPI.java:316)
        at com.bullhorn.dataloader.service.api.BullhornAPI.getRootMetaDataTypes(
BullhornAPI.java:486)
        at com.bullhorn.dataloader.Main.loadCsv(Main.java:68)
        at com.bullhorn.dataloader.Main.main(Main.java:41)
```

I'm not certain what information to give so let me know to add more if needed.

Admin Command Prompt line:

`C:\Users\ccoffman\Desktop\dataloader>java -Dpropertyfile=C:\Users\ccoffman\Desktop\dataloader\dataloader.properties -jar dataloader-importer-1.0.1.jar clientContact C:\Users\ccoffman\Desktop\dataloader\export.csv`

Properties file (attempting to create new clientContacts):
- I included all non-nullable fields
```
clientContactExistField=type,categories.id,owner.id,phone,status,lastName,firstName,name,email,clientCorporation.id,preferredContact,isDeleted,numEmployees

frontLoadedEntities=
numThreads=1
dateFormat=MM/dd/yyyy
listDelimiter=|
pageSize=500
cacheSize=10000

username=(user name)
password=(password)

authorizeUrl=https://auth.bullhornstaffing.com/oauth/authorize
tokenUrl=https://auth.bullhornstaffing.com/oauth/token
loginUrl=https://rest.bullhornstaffing.com/rest-services/login

clientId=workingID
clientSecret=workingSecret
```
![dataloader excel](https://cloud.githubusercontent.com/assets/17765964/14790192/c1ffc970-0ad5-11e6-83c6-882c668abb36.PNG)

Above is the excel file I am loading through DataLoader

The folder that all of these files reside in is C:\Users\ccoffman\Desktop\dataloader

I appreciate any help and feel free to reach out to me via Slack for any discussion as well.

It was also suggested that it could be a field mapping / user type entitlement issue.  The user type has full access to API functionality and I am not certain what to check since they run off of the field names not labels.

Thank you,
Colin

**Comment by ccoffman1** [comment]
I have updated my authorizeURL/tokenUrl/loginUrl to auth2/rest2 and it is giving me a session error.

I am not sure if this means if I have failed further along the process or earlier in the process.

**Comment by ccoffman1** [comment]
Confirmed I had this setup correct originally.  The Fields error comes after authorization.

**Comment by ccoffman1** [comment]
Turns out I was using API style entities I.E "clientCorporatoin"
Data Loader uses full capitalization I.E. "ClientCorporation
